using System;
using System.Threading.Tasks;
using System.Windows.Input;
using CommunityToolkit.Mvvm.ComponentModel;
using ImportadorModelo2.Services;
using ImportadorModelo2.Models;
using ImportadorModelo2.Core.Utils;

namespace ImportadorModelo2.ViewModels
{
    public partial class LoginViewModel : ViewModelBase
    {
        private readonly IAutenticacaoService _autenticacaoService;
        [ObservableProperty]
        private string _email = string.Empty;

        [ObservableProperty]
        private string _password = string.Empty;

        [ObservableProperty]
        private bool _rememberMe;

        [ObservableProperty]
        private bool _showPassword;

        [ObservableProperty(SetterAccessModifier = AccessModifier.Private)]
        private bool _isLoading;

        [ObservableProperty]
        private string? _errorMessage;

        partial void OnEmailChanged(string value)
        {
            ((AsyncRelayCommand)LoginCommand).NotifyCanExecuteChanged();
            ClearError();
        }

        partial void OnPasswordChanged(string value)
        {
            ((AsyncRelayCommand)LoginCommand).NotifyCanExecuteChanged();
            ClearError();
        }

        partial void OnIsLoadingChanged(bool value)
        {
            ((AsyncRelayCommand)LoginCommand).NotifyCanExecuteChanged();
        }

        public LoginViewModel(IAutenticacaoService autenticacaoService)
        {
            _autenticacaoService = autenticacaoService;
            
            LoginCommand = new AsyncRelayCommand(ExecuteLoginAsync, CanExecuteLogin);
            TogglePasswordVisibilityCommand = new RelayCommand(TogglePasswordVisibility);
            ForgotPasswordCommand = new RelayCommand(ExecuteForgotPassword);
            GoogleLoginCommand = new RelayCommand(ExecuteGoogleLogin);
            MicrosoftLoginCommand = new RelayCommand(ExecuteMicrosoftLogin);
            SignUpCommand = new RelayCommand(ExecuteSignUp);

            Task.Run(async () => await CarregarCredenciaisSalvasAsync());
        }

        // Properties generated by [ObservableProperty] above

        public ICommand LoginCommand { get; }
        public ICommand TogglePasswordVisibilityCommand { get; }
        public ICommand ForgotPasswordCommand { get; }
        public ICommand GoogleLoginCommand { get; }
        public ICommand MicrosoftLoginCommand { get; }
        public ICommand SignUpCommand { get; }

        public event Action<Usuario>? LoginSucceeded;
        public event Action<string>? NavigationRequested;

        /// <summary>
        /// Executa o processo de login
        /// </summary>
        private async Task ExecuteLoginAsync()
        {
            try
            {
                IsLoading = true;
                ClearError();

                var hashMaquina = await _autenticacaoService.ObterHashMaquinaAsync();
                var resultado = await _autenticacaoService.LoginAsync(Email, Password, hashMaquina);

                if (resultado.Sucesso && resultado.Usuario != null)
                {
                    if (RememberMe)
                    {
                        await _autenticacaoService.SalvarCredenciaisAsync(Email, RememberMe);
                    }

                    LoginSucceeded?.Invoke(resultado.Usuario);
                }
                else
                {
                    ErrorMessage = resultado.Mensagem ?? "Email ou senha incorretos";
                }
            }
            catch (Exception ex)
            {
                ErrorMessage = "Erro de conexão. Tente novamente.";
                System.Diagnostics.Debug.WriteLine($"Erro no login: {ex.Message}");
            }
            finally
            {
                IsLoading = false;
            }
        }

        /// <summary>
        /// Verifica se o login pode ser executado
        /// </summary>
        private bool CanExecuteLogin()
        {
            return !IsLoading && 
                   !string.IsNullOrWhiteSpace(Email) && 
                   !string.IsNullOrWhiteSpace(Password);
        }

        /// <summary>
        /// Alterna visibilidade da senha
        /// </summary>
        private void TogglePasswordVisibility()
        {
            ShowPassword = !ShowPassword;
        }

        /// <summary>
        /// Navega para recuperação de senha
        /// </summary>
        private void ExecuteForgotPassword()
        {
            NavigationRequested?.Invoke("ForgotPassword");
        }

        /// <summary>
        /// Inicia login com Google
        /// </summary>
        private void ExecuteGoogleLogin()
        {
            NavigationRequested?.Invoke("GoogleLogin");
        }

        /// <summary>
        /// Inicia login com Microsoft
        /// </summary>
        private void ExecuteMicrosoftLogin()
        {
            NavigationRequested?.Invoke("MicrosoftLogin");
        }

        /// <summary>
        /// Navega para cadastro
        /// </summary>
        private void ExecuteSignUp()
        {
            NavigationRequested?.Invoke("SignUp");
        }

        /// <summary>
        /// Limpa mensagem de erro
        /// </summary>
        private void ClearError()
        {
            ErrorMessage = null;
        }

        /// <summary>
        /// Carrega credenciais salvas localmente
        /// </summary>
        private async Task CarregarCredenciaisSalvasAsync()
        {
            try
            {
                var (email, lembrarMe) = await _autenticacaoService.CarregarCredenciaisAsync();
                if (!string.IsNullOrEmpty(email))
                {
                    Email = email;
                    RememberMe = lembrarMe;
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"Erro ao carregar credenciais: {ex.Message}");
            }
        }

    }}